FROM gentoo/stage3-amd64:latest

RUN emerge \
        app-arch/libarchive \
        app-misc/realpath \
        dev-lang/swig \
        dev-libs/uthash \
        dev-util/strace \
        dev-util/valgrind \
        sys-devel/gdb \
        sys-libs/talloc
